config/routes.rb
Rails.application.routes.draw do
  get 'splash/splash'

  resources :notes
  resources :patients
  resources :models

  root 'splash#splash'

  get 'signup' => 'users#new'
  resources :users

  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

end

app/models/model.rb
class Model < ActiveRecord::Base
end

app/models/note.rb
class Note < ActiveRecord::Base
    mount_uploader :picture, PictureUploader
end

app/models/patient.rb
class Patient < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    helper_method :current_user

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def require_user
      redirect_to '/login' unless current_user
    end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_action :require_user, only: [:index, :show]
  before_action :set_model, only: [:show, :edit, :update, :destroy]

  # GET /models
  # GET /models.json
  def index
    @models = Model.all
  end

  # GET /models/1
  # GET /models/1.json
  def show
  end

  # GET /models/new
  def new
    @model = Model.new
  end

  # GET /models/1/edit
  def edit
  end

  # POST /models
  # POST /models.json
  def create
    @model = Model.new(model_params)

    respond_to do |format|
      if @model.save
        format.html { redirect_to @model, notice: 'Model was successfully created.' }
        format.json { render :show, status: :created, location: @model }
      else
        format.html { render :new }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /models/1
  # PATCH/PUT /models/1.json
  def update
    respond_to do |format|
      if @model.update(model_params)
        format.html { redirect_to @model, notice: 'Model was successfully updated.' }
        format.json { render :show, status: :ok, location: @model }
      else
        format.html { render :edit }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1
  # DELETE /models/1.json
  def destroy
    @model.destroy
    respond_to do |format|
      format.html { redirect_to models_url, notice: 'Model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model
      @model = Model.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def model_params
      params.require(:model).permit(:Patients, :title, :surname, :name, :prefname, :age, :gender, :martialstat, :address, :suburb, :postcode, :email, :phone, :mobile, :persontype)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :require_user, only: [:index, :show]
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:timestamp, :tag, :notes, :assessment, :picture, :followup, :nextappointment)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :require_user, only: [:index, :show]
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:title, :surname, :name, :prefname, :age, :gender, :martialstat, :address, :suburb, :postcode, :email, :phone, :mobile, :persontype)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
            session[:user_id] = @user.id
            redirect_to '/'
        else
            redirect_to 'login'
        end
    end

    def destroy
      session[:user_id] = nil
      redirect_to '/'
    end

end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
    before_action :require_user, only: [:index, :show]
  def splash
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to '/'
        else
            redirect_to '/signup'
        end
    end

    private
        def user_params

            params.require(:user).permit(:first_name, :last_name, :email, :password)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cnotes</title>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">CNOTE</a>
    </div>

  </div>
</nav>
<div class="security">
<% if current_user %>
  <ul>
    <li><%= current_user.email %></li>
    <li><%= link_to "Log out", logout_path, method: "delete" %></li>
  </ul>
<% else %>
  <ul>
    <li><%= link_to "Login", 'login' %></a></li>
    <li><%= link_to "Signup", 'signup' %></a></li>
  </ul>
<% end %>
</div>

<div class="container">
  <%= yield %>
</div>
<footer>
  <div class="container">
    Health Hack 2015
  </div>
</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>
</body>
</html>

app/views/models/_form.html.erb
<%= form_for(@model) do |f| %>
  <% if @model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
      <% @model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Patients %><br>
    <%= f.text_field :Patients %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.number_field :title %>
  </div>
  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :prefname %><br>
    <%= f.text_field :prefname %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :martialstat %><br>
    <%= f.text_field :martialstat %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :suburb %><br>
    <%= f.text_field :suburb %>
  </div>
  <div class="field">
    <%= f.label :postcode %><br>
    <%= f.text_field :postcode %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :persontype %><br>
    <%= f.check_box :persontype %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/models/edit.html.erb
<h1>Editing Model</h1>

<%= render 'form' %>

<%= link_to 'Show', @model %> |
<%= link_to 'Back', models_path %>

app/views/models/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Models</h1>

<table>
  <thead>
    <tr>
      <th>Patients</th>
      <th>Title</th>
      <th>Surname</th>
      <th>Name</th>
      <th>Prefname</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Martialstat</th>
      <th>Address</th>
      <th>Suburb</th>
      <th>Postcode</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Mobile</th>
      <th>Persontype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @models.each do |model| %>
      <tr>
        <td><%= model.Patients %></td>
        <td><%= model.title %></td>
        <td><%= model.surname %></td>
        <td><%= model.name %></td>
        <td><%= model.prefname %></td>
        <td><%= model.age %></td>
        <td><%= model.gender %></td>
        <td><%= model.martialstat %></td>
        <td><%= model.address %></td>
        <td><%= model.suburb %></td>
        <td><%= model.postcode %></td>
        <td><%= model.email %></td>
        <td><%= model.phone %></td>
        <td><%= model.mobile %></td>
        <td><%= model.persontype %></td>
        <td><%= link_to 'Show', model %></td>
        <td><%= link_to 'Edit', edit_model_path(model) %></td>
        <td><%= link_to 'Destroy', model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Model', new_model_path %>

app/views/models/new.html.erb
<h1>New Model</h1>

<%= render 'form' %>

<%= link_to 'Back', models_path %>

app/views/models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patients:</strong>
  <%= @model.Patients %>
</p>

<p>
  <strong>Title:</strong>
  <%= @model.title %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @model.surname %>
</p>

<p>
  <strong>Name:</strong>
  <%= @model.name %>
</p>

<p>
  <strong>Prefname:</strong>
  <%= @model.prefname %>
</p>

<p>
  <strong>Age:</strong>
  <%= @model.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @model.gender %>
</p>

<p>
  <strong>Martialstat:</strong>
  <%= @model.martialstat %>
</p>

<p>
  <strong>Address:</strong>
  <%= @model.address %>
</p>

<p>
  <strong>Suburb:</strong>
  <%= @model.suburb %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @model.postcode %>
</p>

<p>
  <strong>Email:</strong>
  <%= @model.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @model.phone %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @model.mobile %>
</p>

<p>
  <strong>Persontype:</strong>
  <%= @model.persontype %>
</p>

<%= link_to 'Edit', edit_model_path(@model) %> |
<%= link_to 'Back', models_path %>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :timestamp %><br>
    <%= f.datetime_select :timestamp %>
  </div>
  <div class="field">
    <%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :assessment %><br>
    <%= f.text_area :assessment %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :followup %><br>
    <%= f.text_area :followup %>
  </div>
  <div class="field">
    <%= f.label :nextappointment %><br>
    <%= f.datetime_select :nextappointment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notes</h1>

<table>
  <thead>
    <tr>
      <th>Timestamp</th>
      <th>Tag</th>
      <th>Notes</th>
      <th>Assessment</th>
      <th>Picture</th>
      <th>Followup</th>
      <th>Nextappointment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.timestamp %></td>
        <td><%= note.tag %></td>
        <td><%= note.notes %></td>
        <td><%= note.assessment %></td>
        <td><%= note.picture %></td>
        <td><%= note.followup %></td>
        <td><%= note.nextappointment %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Timestamp:</strong>
  <%= @note.timestamp %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @note.tag %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @note.notes %>
</p>

<p>
  <strong>Assessment:</strong>
  <%= @note.assessment %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@note.picture_url, :width => 600) if @note.picture.present? %>
</p>

<p>
  <strong>Followup:</strong>
  <%= @note.followup %>
</p>

<p>
  <strong>Nextappointment:</strong>
  <%= @note.nextappointment %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.number_field :title %>
  </div>
  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :prefname %><br>
    <%= f.text_field :prefname %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :martialstat %><br>
    <%= f.text_field :martialstat %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :suburb %><br>
    <%= f.text_field :suburb %>
  </div>
  <div class="field">
    <%= f.label :postcode %><br>
    <%= f.text_field :postcode %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :persontype %><br>
    <%= f.check_box :persontype %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Patients</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Surname</th>
      <th>Name</th>
      <th>Prefname</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Martialstat</th>
      <th>Address</th>
      <th>Suburb</th>
      <th>Postcode</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Mobile</th>
      <th>Persontype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.title %></td>
        <td><%= patient.surname %></td>
        <td><%= patient.name %></td>
        <td><%= patient.prefname %></td>
        <td><%= patient.age %></td>
        <td><%= patient.gender %></td>
        <td><%= patient.martialstat %></td>
        <td><%= patient.address %></td>
        <td><%= patient.suburb %></td>
        <td><%= patient.postcode %></td>
        <td><%= patient.email %></td>
        <td><%= patient.phone %></td>
        <td><%= patient.mobile %></td>
        <td><%= patient.persontype %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @patient.title %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @patient.surname %>
</p>

<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Prefname:</strong>
  <%= @patient.prefname %>
</p>

<p>
  <strong>Age:</strong>
  <%= @patient.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @patient.gender %>
</p>

<p>
  <strong>Martialstat:</strong>
  <%= @patient.martialstat %>
</p>

<p>
  <strong>Address:</strong>
  <%= @patient.address %>
</p>

<p>
  <strong>Suburb:</strong>
  <%= @patient.suburb %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @patient.postcode %>
</p>

<p>
  <strong>Email:</strong>
  <%= @patient.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @patient.phone %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @patient.mobile %>
</p>

<p>
  <strong>Persontype:</strong>
  <%= @patient.persontype %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>

app/views/splash/splash.html.erb
<div class="row">
  <div class="col-sm-4">
    <!--button type="button" class="btn btn-success btn-lg">New Patient</button-->
    <%= link_to 'New Patient', new_patient_path, :class =>'btn btn-success btn-lg' %>
  </div>
  <div class="col-sm-4">
    <!--button type="button" class="btn btn-primary btn-lg">Existing Patient</button -->
    <%= link_to 'Existing Patients', patients_path, :class =>'btn btn-primary btn-lg' %>
  </div>
  <div class="col-sm-4">
    <%= link_to 'Quick Notes', new_note_path, :class => 'btn btn-danger btn-lg'%>
    <!--button type="button" class="btn btn-danger btn-lg">Notes</button>
  </div>
</div>

app/views/users/new.html.erb
<div class="login">
  <div class="container">
    <div class="form">

      <h1>Sign up</h1>

      <%= form_for(@user) do |f| %>
      <%= f.text_field :first_name, :placeholder => "First name" %>
      <%= f.text_field :last_name, :placeholder => "Last name" %>
      <%= f.email_field :email, :placeholder => "Email" %>
      <%= f.password_field :password, :placeholder => "Password" %>
      <%= f.submit "Create an account", class: "btn-submit" %>
      <% end %>


    </div>
  </div>
</div>